const mongoose = require("mongoose");
const db = require("../models");
mongoose.Promise = global.Promise;

//This file empties the Wines collection and inserts the alcohols below 
/*mongoose.connect(
    process.env.MONGODB_URI || "mongodb://localhost/sloshio",
    {
        useMongoClient: true
    }
);
*/
const alcohol = [
        {
            "@search.score": 1,
            "wine_Id": "3",
            "product_Id": "14",
            "isAvailable": 0,
            "name": "2009 Folk Machine Central Coast Pinot Noir",
            "shortDescription": "",
            "longDescription": "This Pinot Noir made by Kenny Likitprakong is one of our perennial bestsellers since Kenny introduced it five years ago. The blend shifts every vintage, but grapes are always from various Monterey vineyards, at least for the most part. For this 2009, 5% fruit from Potter Valley was added. The wine was aged in neutral oak barrel, as the intent is to emphasize the lively fruity freshness of the wine. This is balanced and simply luscious.<br/><br/>Nose and Palate: rock’n smokiness comes out, nice length on palette, lots of strawberry and cherry flavors. ",
            "vintage": null,
            "setting": "",
            "scent": "",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "",
            "varietal": "NA",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "20.00",
            "pairings": [],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "29",
            "product_Id": "10073",
            "isAvailable": 0,
            "name": "2009 Martian Grenache Rose",
            "shortDescription": "",
            "longDescription": "Tight, tart and sophisticated, this wine bears no resemblance to those big-brand roses we’ve all come to know and loathe. It’s brighter, bolder, and actually tastes like the grapes it was made from (100% Grenache). Juicy red-berry flavors come out in full-force, but a light-body and fresh acidity keeps it clean, not cloying. ",
            "vintage": null,
            "setting": "",
            "scent": "",
            "sparkling": "",
            "rose": "",
            "wineType": "white",
            "wineBrand": "",
            "varietal": "Albariño",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "30",
            "product_Id": "10075",
            "isAvailable": 0,
            "name": "2009 Martian Grenache",
            "shortDescription": "",
            "longDescription": "This is definitely a wine you can sink your teeth into! Rich, concentrated dark-berry flavors and notes of spices like cloves and cinnamon lead to a bone-dry finish that goes on and on. ",
            "vintage": "2009",
            "setting": "a moonlight picnic",
            "scent": "",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "",
            "varietal": "Albariño",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Burgers",
                "Poultry",
                "Pork",
                "Mexican",
                "Lamb",
                "Pasta Red Sauce",
                "Cheeses",
                "Cured Meats",
                "Stew",
                "BBQ"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "43",
            "product_Id": "10097",
            "isAvailable": 0,
            "name": "2007 Wanderlust White Wine",
            "shortDescription": "",
            "longDescription": "This harmonious blend of white grapes was created for the Wanderlust festival, a weekend long celebration of life, music and yoga that takes place in various locations throughout the year. Produced naturally and sustainably, this blend is all about balance. Fragrant, spicy notes and crisp acidity offset a lush core of clean fruit flavors. All the elements of this wine work together to create an end result that is far greater than the sum of its parts. This is the perfect wine to sip at the end of a long day, by itself or with a simple plate of fruit and cheese.",
            "vintage": null,
            "setting": "",
            "scent": "",
            "sparkling": "",
            "rose": "",
            "wineType": "white",
            "wineBrand": "",
            "varietal": "NA",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "56",
            "product_Id": "10125",
            "isAvailable": 0,
            "name": "2008 Chateau Beausejour Bordeaux Superior",
            "shortDescription": "",
            "longDescription": "People always assume that any wine from Bordeaux must be uptight and high-maintenance, but in the case of the Chateau Beausejour this couldn’t be further from the truth. Yes, she still carries an air of supreme elegance and good breeding, but she’s just as comfortable at a backyard bbq as she is at a 4-star restaurant and contrary to popular belief an evening with her doesn’t require a limitless spending account, just an open mind and good taste.",
            "vintage": "2008",
            "setting": "From classy to casual, this is a wine you can truly take anywhere",
            "scent": "Spicy blackberry jam",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "",
            "varietal": "NA",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Poultry",
                "Pork",
                "Stew"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "69",
            "product_Id": "10139",
            "isAvailable": 0,
            "name": "2005 Liberalia Cuatro Crianza ",
            "shortDescription": "",
            "longDescription": "An upbringing amongst classical musicians has left the 2005 Liberalia Cuatro with a distinct sense of harmony. Every element of her dynamic personality flows together like a perfectly composed song; from her feisty first impression to the air of soft sensuality that lingers long after she’s gone.",
            "vintage": "2005",
            "setting": "anywhere with live music",
            "scent": "ripe berries with a hint of chocolate",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "",
            "varietal": "NA",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Beef",
                "Pork",
                "Lamb",
                "Veggies"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "70",
            "product_Id": "10140",
            "isAvailable": 0,
            "name": "2010 Los Clop Sur Malbec ",
            "shortDescription": "",
            "longDescription": "Sweet, yet spicy at the same time, this wine has got a flavor all her own. She’s definitely not one to play by the rules and she’s got a feisty rebellious streak that might be slightly intimidating if it weren’t for her warm, accessible personality and undeniable charm.",
            "vintage": "2010",
            "setting": "a long, laid-back lunch at an eclectic cafe",
            "scent": "red berries with a twist of black pepper",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "",
            "varietal": "NA",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Burgers",
                "Lamb",
                "BBQ"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "16",
            "product_Id": "10149",
            "isAvailable": 0,
            "name": "2009 IMT Petit Verdot",
            "shortDescription": "",
            "longDescription": "Petit verdot has long been bringing its deep, inky color and dense fruit to the great Bordeaux blends of the world. However, more recently, the grape has been gaining praise for its own solo career. \r\n\r\nThis is big, big stuff, completely opaque in the glass, gobs of dense black fruit framed by a dry finish with a little punch. You want to give this wine a little air to open up or pair full flavored dishes and marbled cuts of beef. On the nose is a punch of alcohol with a mulch, leather background. The black fruit is hiding beneath. Air and time will help bring the fruit out from underneath.",
            "vintage": "2009",
            "setting": "Reading your favorite novel ",
            "scent": "",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "",
            "varietal": "Albariño",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "19.00",
            "pairings": [],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "83",
            "product_Id": "10165",
            "isAvailable": 0,
            "name": "2009 Manifesto Zinfandel",
            "shortDescription": "",
            "longDescription": "Soft, pretty and undeniably feminine, with an elegant appeal that hints at superior breeding. The Manifesto! Zinfandel is one of those rare, classic beauties whose grace and poise is as alluring as her playful, flirtatious charm.\r\n\r\n\r\n",
            "vintage": "2009",
            "setting": "A swanky evening at a low-key jazz club",
            "scent": "Strawberry and roses",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "",
            "varietal": "NA",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Poultry",
                "Pork",
                "Chocolate Cake",
                "Fruits"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "96",
            "product_Id": "10178",
            "isAvailable": 0,
            "name": "2007 Casa de la Cruz Pinot Noir",
            "shortDescription": "",
            "longDescription": "Wines this sophisticated and mature often come with a certain air of pretension that can be difficult to relate to. Not so with this one! She’s as laid-back and approachable as she is impressive. We might even go so far as to call her fun, or in the right situation casual - all without ever sacrificing the elegance or refinement that make her so special in the first place.",
            "vintage": "2007",
            "setting": "A summertime concert in the park",
            "scent": "Spiced cranberry",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "",
            "varietal": "Albariño",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Pizza",
                "Poultry",
                "Pork",
                "Mexican",
                "Lamb",
                "Chocolate Cake",
                "BBQ"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "119",
            "product_Id": "10197",
            "isAvailable": 0,
            "name": "2009 Love This Life White",
            "shortDescription": "",
            "longDescription": "Charismatic and alluring, the LoveThisLife White practically glows with energy and passion. Her bright personality is undeniably inviting, but it’s the smooth manner in which she presents herself that never fails to win over just about everyone she comes into contact with.",
            "vintage": "2009",
            "setting": "A trendy art gallery opening",
            "scent": "Peach nectar",
            "sparkling": "",
            "rose": "",
            "wineType": "white",
            "wineBrand": "",
            "varietal": "Albariño",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Fish",
                "Shellfish",
                "Oysters",
                "Cheeses",
                "Fruits"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "120",
            "product_Id": "10198",
            "isAvailable": 0,
            "name": "2010 Independent Producers Merlot",
            "shortDescription": "",
            "longDescription": "The House of Independent Producers Merlot is a true rarity - a wine as down-to-earth as she is well bred; as subtle as she is expressive; as elegant as she is accessible. She’s got old-school class and style, but with a thoroughly modern spin. Add to that her playful charm and you’ve got a totally unique reinvention that just might be the new classic.",
            "vintage": "2010",
            "setting": "A midnight movie",
            "scent": "Sun-ripened wildberries",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "",
            "varietal": "Albariño",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Burgers",
                "Pork",
                "Lamb",
                "Pasta Red Sauce",
                "Chocolate Cake",
                "Cured Meats",
                "BBQ"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "106",
            "product_Id": "10205",
            "isAvailable": 0,
            "name": "Bosco dei Cirmioli Montepulciano d'Abruzzo",
            "shortDescription": "",
            "longDescription": "Traditional elegance is the name of the game for this classic Italian beauty and like all the best Italian traditions she manages to combine grace, sensuality and passion into one deceptively simple personality that’s an absolute pleasure to get to know.",
            "vintage": "2010",
            "setting": "An evening stroll amidst beautiful scenery",
            "scent": "Dark chocolate raspberry",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "",
            "varietal": "Albariño",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Pizza",
                "Poultry",
                "Pork",
                "Pasta Red Sauce",
                "Chocolate Cake",
                "BBQ"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "133",
            "product_Id": "10221",
            "isAvailable": 0,
            "name": "2010 House Wine House Red",
            "shortDescription": "",
            "longDescription": "Because she makes any place home you can just as easily serve her at the table as you can at the beach around a bonfire.  There's lots of fruit flavor here, strawberries and cherries, but she's not overly sweet and finishes nice and dry.  ",
            "vintage": "2010",
            "setting": "An evening in the kitchen cooking together",
            "scent": "Juicy red cherry",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "",
            "varietal": "Red Blend",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Burgers",
                "Poultry",
                "Beef",
                "Pork",
                "Pasta Red Sauce",
                "Chocolate Cake",
                "Cured Meats"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "146",
            "product_Id": "10234",
            "isAvailable": 0,
            "name": "2010 Longue Dog White",
            "shortDescription": "",
            "longDescription": "Like the lead actress in a French film her true beauty is subtle and understated but compelling nevertheless.   This Languedoc is a combination of Colombard and Chardonay making her slightly dry and jam packed with apple, pear and citrus.   Pour a glass and drink in all the flavors of a sunny afternoon in southern France.  ",
            "vintage": "2010",
            "setting": "An understated French bistro",
            "scent": "Fresh squeezed lemon",
            "sparkling": "",
            "rose": "",
            "wineType": "white",
            "wineBrand": "",
            "varietal": "NA",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Poultry",
                "Fish",
                "Shellfish",
                "Oysters"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "159",
            "product_Id": "10263",
            "isAvailable": 0,
            "name": "2011 Zull Lust and Laune Blauer Portugieser",
            "shortDescription": "",
            "longDescription": "She's runway pretty and farm-girl friendly, her rosy red cheeks indicative of her dark berry flavors that are nicely accented by fresh plum.  Fresh and lightly tart there's very little pepper or spice making for a red light enough to serve alongside poultry or pork.   If you've never tried a Portugieser, an Austrian and German grape,  allow us the joy and pleasure (Lust and Laune) of introducing you!",
            "vintage": "2011",
            "setting": "Dinner and dancing",
            "scent": "Fresh Plum",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "",
            "varietal": "Albariño",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Poultry",
                "Pork",
                "Fish",
                "Lamb",
                "Pasta Red Sauce",
                "Cured Meats",
                "BBQ"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "160",
            "product_Id": "10264",
            "isAvailable": 0,
            "name": "2011 Triebaumer Trie Red",
            "shortDescription": "",
            "longDescription": "A blend of Zweigelt, St. Laurent and just a hint of Cabernet Sauvignon, she's bursting with cherry and red berry flavors.  The finish is slightly spicy but because she was fermented in stainless steel this wine has no oaky flavors and is well matched with both fish and meats.  If you haven't given red blends a try yet this is the prefect place to start!   ",
            "vintage": "2011",
            "setting": "Happy hour at home",
            "scent": "Spiced Cherry",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "",
            "varietal": "Albariño",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Pizza",
                "Poultry",
                "Pork",
                "Fish",
                "Pasta Red Sauce",
                "Cured Meats",
                "BBQ"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "173",
            "product_Id": "10277",
            "isAvailable": 0,
            "name": "2008 South Hill Sauvignon Blanc",
            "shortDescription": "",
            "longDescription": "Lush and tropical, yet still maintaining an air of elegance and restraint, this wine is a perfect example of what South Africa has to offer. The grapes develop rich and complex flavors over the long growing season, but the relatively cool climate of this region keeps it all in check, combining juicy pineapple and kiwi with a clean and distinctive lemon-lime freshness.",
            "vintage": "2008",
            "setting": "take out and a movie",
            "scent": "fresh lychee",
            "sparkling": "",
            "rose": "",
            "wineType": "white",
            "wineBrand": "",
            "varietal": "Albariño",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Thai",
                "Fish",
                "Shellfish",
                "Oysters",
                "Fruits",
                "Fries"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "186",
            "product_Id": "10290",
            "isAvailable": 0,
            "name": "2009 Quintay \"Q\" Pinot Noir",
            "shortDescription": "",
            "longDescription": "Produced only in limited quantities, this wine showcases the best that Chile has to offer. It's soft, supple, and aromatic in all the right ways with an abundance of red berry flavors and a hint of tangy blood orange. ",
            "vintage": "2009",
            "setting": "a first night of Hanukkah feast",
            "scent": "roasted strawberry",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "",
            "varietal": "NA",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "19.00",
            "pairings": [
                "Burgers",
                "Poultry",
                "Pork",
                "Mexican",
                "Lamb",
                "Cured Meats",
                "BBQ"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "199",
            "product_Id": "10308",
            "isAvailable": 0,
            "name": "2010 Baos Quintas 'Proeza' Dao",
            "shortDescription": "",
            "longDescription": "Made from native Portugese varietals this wine is striking, yet familiar. It's spicy and smooth at the same time with just a hint of bright acidity to keep things lively. It's ideal for pairing with food, but it's certainly got enough character to shine on it's own as well.",
            "vintage": "2010",
            "setting": "a corner table for two at a small, hidden bistro",
            "scent": "crushed clove",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "",
            "varietal": "Albariño",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Pizza",
                "Poultry",
                "Pork",
                "Mexican",
                "Lamb",
                "Pasta Red Sauce",
                "Cured Meats",
                "Stew",
                "BBQ"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "209",
            "product_Id": "10318",
            "isAvailable": 0,
            "name": "2011 Vinum Chenin Blanc-Viognier",
            "shortDescription": "",
            "longDescription": "Both Chenin Blanc and Viognier originally come from France, but one we can't help but love this modern California blend. Incredibly fragrant, rich and juicy, this is the perfect wine for pairing with fresh seafood, thai curry or even sushi.",
            "vintage": "2011",
            "setting": "a lazy weekend lunch",
            "scent": "apricot nectar",
            "sparkling": "",
            "rose": "",
            "wineType": "white",
            "wineBrand": "",
            "varietal": "White Blend",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Thai",
                "Fish",
                "Shellfish",
                "Oysters",
                "Sushi",
                "Chinese",
                "Salad",
                "Cheeses",
                "Cured Meats",
                "Veggies",
                "Fruits",
                "Fries"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "210",
            "product_Id": "10319",
            "isAvailable": 0,
            "name": "2012 Goddess Sweet White",
            "shortDescription": "",
            "longDescription": "A sweet treat made from Muscat, Torrontes and Chardonnay grown in the heart of Argentina. This wine starts with an abundance of floral aromas leading into plenty of bright tropical flavors, but the best part is, this wines sweetness comes from all natural processes which leaves it tasting most of all like pure, perfectly ripe fruit.",
            "vintage": "2012",
            "setting": "A sweet dessert for two",
            "scent": "candied rose petal",
            "sparkling": "",
            "rose": "",
            "wineType": "white",
            "wineBrand": "",
            "varietal": "Zinfandel",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Thai",
                "Chinese",
                "Chocolate Cake",
                "Fruits",
                "BBQ",
                "Fries"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "223",
            "product_Id": "10332",
            "isAvailable": 0,
            "name": "2011 Nugan \"Third Generation\" Cabernet Sauvignon",
            "shortDescription": "",
            "longDescription": "",
            "vintage": "2011",
            "setting": "",
            "scent": "",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "",
            "varietal": "Albariño",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "236",
            "product_Id": "10363",
            "isAvailable": 0,
            "name": "Casas del Bosque Pinot Noir",
            "shortDescription": "",
            "longDescription": "This is certainly not the first Pinot Noir from Chile that we've featured on Club W - and with good reason! The wines being made in this region seem to just keep getting better and better. This is another solid example with soft fruit flavors, hints of warm spice and a sense of balance that's truly elegant and graceful.",
            "vintage": "2011",
            "setting": "A lively cocktail party",
            "scent": "spiced cherries",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "",
            "varietal": "Pinot Noir",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "19.00",
            "pairings": [
                "Burgers",
                "Pizza",
                "Poultry",
                "Pork",
                "Mexican",
                "Lamb",
                "Chinese",
                "Pasta Red Sauce",
                "Chocolate Cake",
                "Cheeses",
                "Cured Meats",
                "Stew",
                "BBQ"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "249",
            "product_Id": "10376",
            "isAvailable": 0,
            "name": "2010 MRLT",
            "shortDescription": "",
            "longDescription": "No longer can we stand idly by while people badmouth merlot when there are so many great examples being produced including this wine.   The plum and black berry flavors make this an excellent wine to pair with grilled meats.  A long smooth finish makes the perfect compliment to the smokiness the grill's char lends to the food.   ",
            "vintage": "2010",
            "setting": "A movie at home",
            "scent": "Plum",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "MRLT",
            "varietal": "Merlot",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Beef",
                "Ribs",
                "Lamb",
                "Pasta Red Sauce",
                "Chilli",
                "BBQ"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "250",
            "product_Id": "10377",
            "isAvailable": 0,
            "name": "2011 Score Red Blend",
            "shortDescription": "",
            "longDescription": "The beauty of a red blend is the ability to achieve a wide variety of fruit flavors in a single wine, including in this case strawberry, blueberry, blackberry and plum.   Lay these layers of fruit on top of each other and you have a jelly doughnut in a glass.  ",
            "vintage": "2011",
            "setting": "Under a starry sky and dreaming",
            "scent": "Strawberry",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "Score",
            "varietal": "Red Rhone Blend",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Burgers",
                "Beef",
                "Ribs",
                "Mexican",
                "Pasta Red Sauce",
                "BBQ",
                "Fries"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "263",
            "product_Id": "10395",
            "isAvailable": 0,
            "name": "2010 Chateau Le Bergey Bordeaux",
            "shortDescription": "",
            "longDescription": "Made mostly from Merlot, this Bordeaux comes across softer and subtler than the other reds we are featuring this month.  When people think of red wines they don't immediately think of pairing with cheese but the Chateau Le Bergey will change your mind and open your eyes to why people covet Bordeaux wine so much.  ",
            "vintage": "2010",
            "setting": "An outdoor cafe",
            "scent": "Raspberry",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "",
            "varietal": "Merlot Blend",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Pizza",
                "Beef",
                "Lamb",
                "Cheeses",
                "Stew"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "276",
            "product_Id": "10412",
            "isAvailable": 0,
            "name": "2009 Nugan Vision Chardonnay",
            "shortDescription": "",
            "longDescription": "Australian wines are known for their big, bold, flavorful style, and this Chardonnay definitely lives up to its roots. This wine is a compilation of a few different vineyard sites. A short amount of oak aging provides an inviting aroma of vanilla and nutmeg with notes of sweetness. You’ll taste toasty flavors of canned peach and creamy lemon custard with a layer of spice. Pair this with a creamy sauce to pull out that flavor in the wine or with an easy, Australian dish like shrimp on the barbie.",
            "vintage": "2009",
            "setting": "A backyard BBQ",
            "scent": "Canned peach",
            "sparkling": "",
            "rose": "",
            "wineType": "white",
            "wineBrand": "",
            "varietal": "Chardonnay",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Poultry",
                "Pork",
                "Chinese",
                "Pasta Cream Sauce",
                "Cured Meats",
                "BBQ"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "300",
            "product_Id": "10440",
            "isAvailable": 0,
            "name": "2012 Les Hauts De Legarde",
            "shortDescription": "",
            "longDescription": "A French bottle lovingly grown in the fields of Bordeaux’s largest organic vineyard, it’s a great white blend for fans of crisp, refreshing wines. The Sauvignon Blanc brings a bright grassiness, while the Sémillon rounds out the palate with a pear flavor and floral bouquet. A whiff from your glass conjures up a sunny summer day with its scents of warm lemon lime and citrus. Enjoy it with light snacks during the happiest hour on a sunny patio.\r\n\r\nWhite Bordeaux blend: 60% Sauvignon Blanc, 40% Sémillon",
            "vintage": "2012",
            "setting": "Happy hour",
            "scent": "Green Apple",
            "sparkling": "",
            "rose": "",
            "wineType": "white",
            "wineBrand": "",
            "varietal": "Viura",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Fish",
                "Shellfish",
                "Sushi",
                "Pasta Cream Sauce",
                "Veggies"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "313",
            "product_Id": "10456",
            "isAvailable": 0,
            "name": "2012 Mi Terruño Sweet Torrontes",
            "shortDescription": "",
            "longDescription": "A distinctly Argentine grape, the Torrontés fruit produces intensely aromatic wines and Mi Terruño’s creation doesn’t disappoint. This bottle is like drinking a bouquet of crisp, white gardenias. Light-bodied and slightly sweet, a chilled glass will highlight the grape’s notes of honeysuckle and citrus blossoms met by a taste of white peaches and a satiating finish. Enjoy it with tough-to-pair spicy Asian dishes where the wine’s sugar content will tame the food’s heat.",
            "vintage": "2011",
            "setting": "Wandering through a botanical garden",
            "scent": "Gardenias",
            "sparkling": "",
            "rose": "",
            "wineType": "white",
            "wineBrand": "",
            "varietal": "Torrontés",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Thai",
                "Chinese",
                "Fruits"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "326",
            "product_Id": "10470",
            "isAvailable": 0,
            "name": "2010 Château Beauséjour Pentimento",
            "shortDescription": "",
            "longDescription": "Club W Winemaker Partner Michele D'Aprix describes winemaking as an ever-progressing, collaborative art. Hence the name of her artful cuvée, Pentinmento. The word refers to the tradition of Renaissance artists who painted over works that didn’t sell. The layers of paint offered subsequent changes in composition or process along the way, all contributing to the final work. So, as the first proprietary label Michele has made, she says that “the name was given in gratitude for all those involved in the continuous effort that is required to make great wine.” Michele works with the greatest vineyards and winemakers in Bordeaux to create a beautiful wine that is only fully realized, like a great painting, after all the layers are in place. Full-bodied and slightly dry, it’s got the structural complexity worthy of aging but with the holidays on deck, good luck resisting temptation!\r\nGrapes: 75% Merlot, 25% Cabernet Franc",
            "vintage": "2010",
            "setting": "A night filled with celebration and family",
            "scent": "Chocolate Covered Cherries",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "",
            "varietal": "Bordeaux Blend",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "25.00",
            "pairings": [
                "Burgers",
                "Poultry",
                "Beef",
                "Lamb",
                "Cheeses"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "339",
            "product_Id": "10486",
            "isAvailable": 0,
            "name": "2011 Horse and Plow Grist Vineyard Zinfandel",
            "shortDescription": "",
            "longDescription": "The passion project of Club W Winemaker Partner Chris Condos and his wife Suzanne, Horse and Plow wines were created for everyday enjoyment. Their Zinfandel comes from the organically farmed Grist Vineyard, a site known for cult wines such as Turley and The Prisoner. Unlike most jammy Zins, Horse and Plow’s is supremely balanced. It’s packed with candied currant, blackberry, leather and spice flavors, yet it retains its natural acidity to ensure it never gets too sweet. With only 250 cases in the whole world, Club W is one of the few places you can claim your bottle (or two).",
            "vintage": "2011",
            "setting": "Any table featuring farm to table ingredients",
            "scent": "Leather",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "",
            "varietal": "Zinfandel",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "30.00",
            "pairings": [
                "Poultry",
                "Beef",
                "Lamb"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "340",
            "product_Id": "10487",
            "isAvailable": 0,
            "name": "2011 Hobo Wine Company Sceales Vineyard Grenache",
            "shortDescription": "",
            "longDescription": "Club W Winemaker Partner and former pro skateboarder Kenny Likipkarong believes in his heart that “every wine has a story” and his Grenache follows suit. One day his daughter’s preschool teacher approached him: Was he interested in grapes her father was selling?  Skeptical, but wanting to make a good impression for his daughter’s sake, Kenny obliged. He was pleasantly surprised to discover the man was offering exceptionally unique Grenache grapes grown on the oldest vines in Sonoma County. The resulting wine is a vivid red with fresh, spice-accented berry aromas. Syrupy and light on its feet, this Grenache offers silky tannins and lasting flavors of rose and cinnamon, making it the perfect companion for carne asada, lamb chops or Moroccan food.",
            "vintage": "2011",
            "setting": "Wherever your hobo heart takes you on your travels",
            "scent": "Spice Cake",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "",
            "varietal": "Grenache",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "26.00",
            "pairings": [
                "Beef",
                "Mexican",
                "Lamb"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "353",
            "product_Id": "10523",
            "isAvailable": 0,
            "name": "2011 Pinuaga La Senda",
            "shortDescription": "",
            "longDescription": "The Pinuaga estate takes their 200 years of winemaking experience and applies it to some of the most forward thinking wine practices in all of Spain. They focus on natural winemaking, balancing artisan and innovative techniques to give their wines a modern twist. La Senda is an unoaked red sourced from vines grown using sustainable agriculture techniques and fermented with native yeasts. The Merlot is an ideal complement to the Tempranillo in this blend, producing a flavorful, young wine with intense aromas of fresh jam, candied plums, and a little bit of spice. Medium-bodied, fruit-forward flavors will hit your palate in this modern Spanish wine.\r\nGrapes: 80% Merlot, 20% Tempranillo",
            "vintage": "2011",
            "setting": "Cozying up on a cold winter's eve",
            "scent": "Sugar Plums",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "",
            "varietal": "Tempranillo",
            "originState": "",
            "originRegion": "",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Pizza",
                "Pasta Red Sauce",
                "Cheeses",
                "Cured Meats",
                "Veggies",
                "Stew"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "366",
            "product_Id": "10539",
            "isAvailable": 0,
            "name": "2012 The Independent Pinot Noir",
            "shortDescription": "",
            "longDescription": "\r\nAbout this W Collaboration:\r\nChris Condos comes from a large Greek family with a long history of winemaking. For him, the best way to pay respect to his family’s tradition was to fly in the face of convention. Chris is renowned for being on the forefront of organic winemaking and farming practices, launching his first vineyard in 1997 to focus on hand-crafted wines using Advanced Organics - practices that are still considered progressive even by today’s standards. Disregarding what may be “en vogue” in the wine world at any given time, Chris is a true Independent who instead believes in following his heart and respecting the harvest. To him, that means finding delicious fruit - whatever varietal it may be - and intervening as little as possible in the grape’s growth to produce wines with finesse and freshness that lets the grape’s natural flavors shine through. \r\n\r\nMade exclusively for Club W, a taste of his Pinot Noir is all-natural bliss. Chris will tell you, “I don’t think I did anything fancy to it.” And that is the point. Chris takes great care of his vineyards and wants the fruit’s pure flavors to be the focus. In this case, you’ll savor beautiful cherry notes with “really neat underlying spices of cinnamon and nutmeg” while enjoying a super soft texture as you drink. It’s a delightfully balanced wine that stands on its own. ",
            "vintage": "2012",
            "setting": "After shopping the farmers market",
            "scent": "Nutmeg",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "The Independent",
            "varietal": "Pinot Noir",
            "originState": "California",
            "originRegion": "Central Coast",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [],
            "body": [
                "medium"
            ],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[\"room temperature\"]",
            "sweetness": [
                "dry"
            ],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "379",
            "product_Id": "10552",
            "isAvailable": 0,
            "name": "2013 Banyan Gewurtztraminer",
            "shortDescription": "",
            "longDescription": "Although Gewurztraminer can be quite sweet, this wine keeps it all in balance with a good dose of acidity thanks to the cool, foggy climate it's grown in. The result is a wine whose aromatics overshadow it's sweetness, with a range of spicy, tropical flavors that will leave your mouth watering.",
            "vintage": "2013",
            "setting": "late-night sushi",
            "scent": "crushed ginger",
            "sparkling": "",
            "rose": "",
            "wineType": "white",
            "wineBrand": "",
            "varietal": "Albariño",
            "originState": "California",
            "originRegion": "Monterey",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "380",
            "product_Id": "10553",
            "isAvailable": 0,
            "name": "2012 Más Que Vinos Ercavio Blanco",
            "shortDescription": "",
            "longDescription": "Más Que Vinos (“more than wine”) is a tale of friendship and adventure. During a trip to the town of Toledo, three winemaker pals made sure to visit the local vineyards. After seeing the vines, they grew enamoured with the idea of making wine with the indigenous grapes and spent the next year renovating an old, dilapidated winery so they could produce delicious, local and organic wine. Their unoaked Blanco is made of 100% Airén - the most widely planted grape in Spain, but interestingly, isn’t found anywhere else in the world. Delightfully light and crisp, its zesty lemon and green apple aromas link up with candied citrus flavors in a wine that will appeal to any Pinot Grigio lover.",
            "vintage": "2012",
            "setting": "With the royal fam",
            "scent": "Meyer Lemon",
            "sparkling": "",
            "rose": "",
            "wineType": "white",
            "wineBrand": "",
            "varietal": "Ercavio",
            "originState": "",
            "originRegion": "Castilla-La Mancha",
            "originCountry": "Spain",
            "price": "13.00",
            "pairings": [
                "Fish",
                "Shellfish",
                "Oysters",
                "Sushi",
                "Salad",
                "Veggies"
            ],
            "body": [],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[]",
            "sweetness": [],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "393",
            "product_Id": "10567",
            "isAvailable": 0,
            "name": "2013 Agua Negra Merlot",
            "shortDescription": "",
            "longDescription": "Shielded from the ocean’s influence by a coastal range of hills, the Curicó Valley creates the ideal climate for big-shouldered reds that will impress any Cabernet or red blend drinker. So get ready, this is a Merlot with a lot of character. \r\n\r\nIt’s classic for Chilean wines to carry a an extra oomph of herbal notes outside of the fruit, creating a wine that is really complex. See what all this flav-ah is about and dive into Agua Negra’s labyrinth of aromas as you savor coffee, dried herbs and plum along with a hint of bell pepper - a classic Merlot scent. It’s balanced structure makes it the perfect wine for seasonal fall dishes.",
            "vintage": "2013",
            "setting": "A rich, hearty meal",
            "scent": "Coffee, plum, jam, bell pepper, mint",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "Agua Negra",
            "varietal": "Merlot",
            "originState": "",
            "originRegion": "Central Valley",
            "originCountry": "Chile",
            "price": "13.00",
            "pairings": [
                "Burgers",
                "Pork",
                "Lamb",
                "Stew"
            ],
            "body": [
                "full"
            ],
            "cider": "",
            "closure": [
                "cork"
            ],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[\"room temperature\"]",
            "sweetness": [
                "dry"
            ],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "403",
            "product_Id": "10585",
            "isAvailable": 0,
            "name": "2012 Poor Man's Pinot Blanc",
            "shortDescription": "",
            "longDescription": "Pinot Blanc is the \"Poor Man's Chardonnay\" no more. This wine is all about challenging that tired stereotype to demonstrate all the deliciousness this grape has to offer. While often compared to Chardonnay because of its uncanny resemblance both on the vine and in the way it’s produced, Pinot Blanc leaves behind that round, buttery taste behind in favor of a more refreshing minerality. This poor fella will present you with a very pretty floral bouquet, but it also knows how to pack a mid-palate punch with a bite of honey-dipped apple followed by some incredible stainless steel crispness to finish your sip. Match him up with a homemade brunch that’s as simple or fancy as you want. Poor Man won’t discriminate between the rich or the broke: it is delicious for all.",
            "vintage": "2012",
            "setting": "Homemade brunch",
            "scent": "Honey-Dipped Apple",
            "sparkling": "",
            "rose": "",
            "wineType": "white",
            "wineBrand": "Poor Man's",
            "varietal": "Pinot Blanc",
            "originState": "California",
            "originRegion": "Monterey",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Fish",
                "Veggies"
            ],
            "body": [
                "medium"
            ],
            "cider": "",
            "closure": [],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[\"chilled\"]",
            "sweetness": [
                "dry"
            ],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "416",
            "product_Id": "10600",
            "isAvailable": 0,
            "name": "2013 Akoya Chardonnay",
            "shortDescription": "",
            "longDescription": "For nearly two-thousand years, the Ama, a sisterhood of Japanese free divers, have created a remarkable livelihood harvesting saltwater pearls with nothing more than a mask and flippers. Untouched by oak, the Akoya Chardonnay highlights true beauty in it's natural form; a mouthful of just-picked honeydew, crisp apples and baked pear to give it a round body that beautifully pairs with roasted trout or sea bass. Elegant and pure like a pearl itself, Akoya has a smooth luster that allows the light to dance in your glass.",
            "vintage": "2013",
            "setting": "Sailing in the sea breeze",
            "scent": "Mango Chutney",
            "sparkling": "",
            "rose": "",
            "wineType": "white",
            "wineBrand": "Akoya",
            "varietal": "Chardonnay",
            "originState": "California",
            "originRegion": "Carneros-Sonoma",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Fish",
                "Shellfish",
                "Pasta Cream Sauce",
                "Salad",
                "Fruits"
            ],
            "body": [
                "medium"
            ],
            "cider": "",
            "closure": [
                "cork"
            ],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[\"chilled\"]",
            "sweetness": [
                "dry"
            ],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "429",
            "product_Id": "10615",
            "isAvailable": 0,
            "name": "2012 Pregame Red Blend",
            "shortDescription": "",
            "longDescription": "It's Friday night. You've had a long week, you're ready to get down with your crew dancing the night away, and you need a crowd-pleaser. Enter Pregame. With dark, fruity blackberry notes and a smooth finish, this juicy red blend is bound to get the party started. A berry explosion of taste makes for a super-drinkable red to kick off your weekend of fun. Get it down and head on out. \r\n\r\nWhy you'll love it: Pregame is a wild berry explosion of smells and flavor, but won’t be overly jammy on your palate. Instead, it’s silky smooth texture makes it highly drinkable - a.k.a. nice and easy down the hatch ;-)\r\n\r\nGrapes: Cabernet Sauvignon, Merlot, Zinfandel, Ruby Cab",
            "vintage": "2012",
            "setting": "",
            "scent": "Wild Berry Mix",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "Pregame",
            "varietal": "Red Blend",
            "originState": "California",
            "originRegion": "Paso Robles",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Burgers",
                "Poultry",
                "Cheeses"
            ],
            "body": [
                "full"
            ],
            "cider": "",
            "closure": [
                "cork"
            ],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[\"room temperature\"]",
            "sweetness": [
                "dry",
                "slightly sweet"
            ],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "430",
            "product_Id": "10616",
            "isAvailable": 0,
            "name": "2013 Alcalá Monastrell",
            "shortDescription": "",
            "longDescription": "Catalan for “citadel”, Alcalà is the signifying fortress of Alicante, shielding outsiders from disrupting their Moorish empire with it’s walls of immaculate strength. With roots in this sovereign place, the Alcalá Monastrell will leave a lasting, daring and distinct impression on your palate. A strength of orange zest, earth, and strawberry flavors flow from this bold, beautiful wine. \r\n\r\nWhy you’ll love it: The rich Monastrell grape - or Mourvèdre as it’s known in France - takes a spotlight in this all-natural wine while its fermentation in stainless steel adds a liveliness of orange zest to it’s dense and jammy flavor (as opposed to the mellowing effects of oak). A perfect example of why Spanish wines are a fast growing trend among American wine drinkers, it’s the perfect combo of ripe fruit flavors we’re used to in the New World, plus a little funky edge provided by Spain.",
            "vintage": "2013",
            "setting": "",
            "scent": "Dusty Orange",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "Alcalá",
            "varietal": "Mourvedre",
            "originState": "",
            "originRegion": "Alicante",
            "originCountry": "Spain",
            "price": "13.00",
            "pairings": [
                "Beef",
                "Ribs",
                "Pork"
            ],
            "body": [
                "light"
            ],
            "cider": "",
            "closure": [
                "cork"
            ],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[\"room temperature\"]",
            "sweetness": [
                "dry"
            ],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "456",
            "product_Id": "10659",
            "isAvailable": 0,
            "name": " 2013 Rambutan Gewürztraminer",
            "shortDescription": "",
            "longDescription": "Aromatic and tropical, Gewürztraminer is a rarity to find growing in the land of the country’s best Chardonnay. While Russian River is known for its cool climate expressions of the big name grapes (which often fetch much higher prices), this is a chance to try the exotic side of the famous California region. \r\n\r\nNot only is the style of this grape incredibly exotic with its scents of lychee fruit, juicy grapefruit, and elderflower, it’s a fantastic wine to pair spice-laden Indian and Middle Eastern fare. Rambutan’s flavors are beautifully balanced thanks the cooling fog that blankets the Russian River Valley at night. The fog acts as a natural air conditioning, making the grapes ripen slowly and creates a wine with higher acidity - a refreshing counterpart to Rambutan’s sweet, fruity flavor. ",
            "vintage": "2013",
            "setting": "",
            "scent": "Lychee, starfruit, elderflower",
            "sparkling": "",
            "rose": "",
            "wineType": "white",
            "wineBrand": "Rambutan",
            "varietal": "Gewürztraminer",
            "originState": "California",
            "originRegion": "Sonoma",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Thai",
                "Salad",
                "Fruits",
                "Indian"
            ],
            "body": [
                "light"
            ],
            "cider": "",
            "closure": [
                "screwcap"
            ],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[\"chilled\"]",
            "sweetness": [
                "slightly sweet"
            ],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "469",
            "product_Id": "10691",
            "isAvailable": 0,
            "name": "2013 Brethren of the Road Red Blend",
            "shortDescription": "",
            "longDescription": "We’re huge fans of Kenny Likitprakong’s style. Heavily geared toward natural winemaking practices means he focuses on getting the purest expression out of his grapes - with little manipulation in the winery. This also means he has to find the best vineyards in Mendocino to work with, which luckily he’s very good at.\r\n\r\nWhen we first spoke with Kenny after harvest, he had some funky fruit he wanted to work with. We’d never seen a wine made with these varietals, and probably would never have sought them out, but this was something Kenny wanted to try for a long time. The result is a red with a crazy mix of flavor. Italian Negroamaro brings a spiciness and texture to nose, while Barbera adds a tart punch on the finish. Those two varieties, by the way, are never blended together even in Italy… and are never mixed with the Portuguese Touriga Nacional. But as a relative of Tempranillo, Touriga’s style falls right in the middle of the two Italian grapes and here, acts as the glue that brings everything together. ",
            "vintage": "2013",
            "setting": "Family dinner",
            "scent": "Cherry cola, orange peel, pine, cinnamon",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "Brethren of the Road",
            "varietal": "Red Blend",
            "originState": "California",
            "originRegion": "Mendocino",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Pizza",
                "Beef",
                "Pasta Red Sauce"
            ],
            "body": [
                "medium"
            ],
            "cider": "",
            "closure": [
                "cork"
            ],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[\"room temperature\"]",
            "sweetness": [
                "dry"
            ],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "470",
            "product_Id": "10714",
            "isAvailable": 0,
            "name": "2012 Prismus® Cabernet Franc",
            "shortDescription": "",
            "longDescription": "Cabernet Franc can go two ways: Loire-style or Bordeaux-style. The Loire typically produces a Cab Franc that is lighter-bodied with leafy green flavors, whereas Bordeaux’s version is a bit beefier. Not only do the grapes ripen in a warmer climate, making the fruit’s flavors more concentrated, but Bordeaux-style also means oak aging. So expect a wallop of rich, toasty flavor. While Cab Franc is not common in California’s Lake County, we believe this region has the greatest potential for making a Bordeaux-style right here at home.\n\nPrismus® is our ode to the bold Cabernet Francs Bordeaux is famous for; our Cheval Blanc so to speak. Smell its rich perfume of toasty cinnamon spice and candied blackberry syrup… so delicious. On the palate it’s full-bodied and will coat your mouth with tons of texture but at the same time is really refined. Trademark of wines that spend some time in barrel is this great mouthfeel and integrated flavors. Pair it with a rich beef or lamb dish with rosemary and tarragon. It’s the kind of wine we see fitting in perfectly at a holiday dinner party.",
            "vintage": "2012",
            "setting": "Special occasion",
            "scent": "cassis, cinnamon toast, raspberry syrup, allspice",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "Prismus",
            "varietal": "Cabernet Franc",
            "originState": "California",
            "originRegion": "Lake County",
            "originCountry": "United States",
            "price": "16.00",
            "pairings": [],
            "body": [
                "full"
            ],
            "cider": "",
            "closure": [
                "cork"
            ],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[\"room temperature\"]",
            "sweetness": [
                "dry"
            ],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "483",
            "product_Id": "10765",
            "isAvailable": 0,
            "name": "2014 Zwicker Edelzwicker",
            "shortDescription": "",
            "longDescription": "In Alsace, the best white wine has never been a single varietal but rather, a blend made from their four noble grapes: Riesling, Gewürztraminer, Pinot Gris and/or Muscat. This wine called Edelzwicker, edel = noble and zwicker = blend, is the perfect combo of fruit and freshness. For our version, winemaker Kenny Likitprakong emulated the traditional off-dry style (meaning it has a hint of sweetness) by blending Riesling and Gewürztraminer. The result is pleasant and easy-drinking, or as Kenny puts it, “I like the idea of this being an everyday wine made from ‘noble’ varieties.”\r\n\r\nZwicker starts off with a heady and exotic perfume of aromas; a little spice on the nose met by tropical flowers and fruit. The mix of two varietals creates the perfect balance as Riesling gives the wine a racy (or acidic) green apple flavor, and Gewürztraminer brings floral and fleshy fruit notes. Made using traditional Alsatian methods, Zwicker is true to the wine you would find in its native cool climate. For food, pair the sweet notes with Japanese food, spicy spring rolls, or even a rustic ham and cheese sammy!",
            "vintage": "2014",
            "setting": "A light, healthy dinner",
            "scent": "White flower, jasmine, green apple, orange rind, lychee",
            "sparkling": "",
            "rose": "",
            "wineType": "white",
            "wineBrand": "Zwicker",
            "varietal": "White Blend",
            "originState": "California",
            "originRegion": "Monterey",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Pork",
                "Thai",
                "Sushi",
                "Salad",
                "Veggies"
            ],
            "body": [
                "light"
            ],
            "cider": "",
            "closure": [
                "cork"
            ],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[\"chilled\"]",
            "sweetness": [
                "dry",
                "slightly sweet"
            ],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "496",
            "product_Id": "10778",
            "isAvailable": 0,
            "name": "2010 Un Paso Más Red Blend",
            "shortDescription": "",
            "longDescription": "Un Paso Más stands for one more step, or one more chapter, and change has been a long time coming. After decades of flying under the radar to neighboring France, Spain has put its mark on the <a target=“_blank” href=“http://juice.clubw.com/jargon/old-world”>Old World</a>. Known for their spunky flavor, wines from this region are unlike any of their European counterparts. Step into a journey and taste a bottle from one of our favorite places for reds with some sass. \n\nThe 2010 Un Paso Más is a celebration of the Spanish winemaking style. It’s a “barrica” blend of <a target=“_blank” href=“http://juice.clubw.com/jargon/cabernet-sauvignon”>Cabernet Sauvignon</a> and <a target=“_blank” href=“http://juice.clubw.com/jargon/syrah----shiraz”>Syrah</a>, a mix of old and new where modern varieties meet traditional Spanish techniques. Known for a signature style of letting the wine age in oak for long periods of time, Spanish winemakers use these barricas to create a soft texture and impart secondary flavors of earth, spice and herbs. With a little age in the bottle, its dark fruit, earthy flavor and big <a target=“_blank” href=“http://juice.clubw.com/jargon/tannins”>tannins</a> definitely make it a candidate for a fancy steak dinner!",
            "vintage": "2010",
            "setting": "Special occasion",
            "scent": "cedar, blackberry, dried herbs, licorice, fig, mint",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "Un Paso Más",
            "varietal": "Spanish Red Blend",
            "originState": "",
            "originRegion": "Castilla y Leon",
            "originCountry": "Spain",
            "price": "13.00",
            "pairings": [],
            "body": [
                "full"
            ],
            "cider": "",
            "closure": [
                "cork"
            ],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[\"room temperature\"]",
            "sweetness": [
                "dry"
            ],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "506",
            "product_Id": "10818",
            "isAvailable": 0,
            "name": "2013 Alma Libre Red Blend",
            "shortDescription": "",
            "longDescription": "Alma Libre is a free-spirited blend created by our winemaker partner <a target=“_blank” href=“https://www.youtube.com/watch?v=8jQ1_vRiddc”>Luca Hodgkinson</a>. A man driven by travel and adventure, Luca’s journey around the world eventually led him to Chile, where his passion for wine and exploration combined. Growing up on a winery in the Priorat (where he still runs the family’s operation), Luca went on to make wine all over Spain, France, and Italy. But when his work brought him to the vineyards of South America, Luca finally felt at home. Alongside the wild, coastal mountain ranges of Colchagua Valley, he describes winemaking in Chile as “writing the pages of a blank book.” \n\nLuca’s blend takes two of Colchagua’s most popular varieties - Carménère and Cabernet Franc - to create a true reflection of Chilean flavor. Earthy and floral aromas are complemented by the wine’s <a target=“_blank” href=“http://juice.clubw.com/jargon/silky”>silky</a> body, a touch of spice, and <a target=“_blank” href=“http://juice.clubw.com/jargon/dry”>dry</a> finish. As Luca explains, “My friends say I have a style of the palate; smooth and drinkable. This blend is easy drinking, which is what I love. Even when the wines are complex, I want them to be enjoyable.”",
            "vintage": "2013",
            "setting": "Dinner party",
            "scent": "Wet earth and moss, white and pink pepper, blueberry, ripe currant, orchids",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "Alma Libre",
            "varietal": "Red Blend",
            "originState": "",
            "originRegion": "Colchagua Valley",
            "originCountry": "Chile",
            "price": "13.00",
            "pairings": [
                "Poultry",
                "Fish",
                "Veggies"
            ],
            "body": [
                "medium"
            ],
            "cider": "",
            "closure": [
                "cork"
            ],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[\"pop it open 20 minutes before serving\"]",
            "sweetness": [
                "dry"
            ],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "519",
            "product_Id": "10880",
            "isAvailable": 0,
            "name": "2014 Rambutan Muscat Blanc",
            "shortDescription": "",
            "longDescription": "Muscat Blanc, more formally known as Muscat Blanc à Petits Grains, is one of the oldest grape varieties in the world. It’s been around for so long that winemakers have produced it in a number of styles and sweetness levels, making everything from sparkling to dessert wine (it’s also the grape Moscato is made from). But finding a bottle of dry Muscat Blanc is a bit of a rarity…unless you’re chillin’ in the south of France where it’s favored as the table white of choice. \n\nHighly aromatic, Muscat Blanc exudes rich scents of tropical fruit and florals. Even on the vine, it’s revered for having a heavy perfume that attracts bees. But this wine is a bit of a trickster. The <a target=“_blank” href=“http://juice.clubw.com/jargon/nose”>nose</a> has you thinking it will be sweet, but on the palate it's bone dry, almost reminding us of an Italian Pinot Grigio. It’s clean and <a target=“_blank” href=“http://juice.clubw.com/jargon/crisp”>crisp</a> with a little bit of kiwifruit and green apple. Also, don’t forget to keep smelling! As the wine warms up in your glass, those aromatics will get stronger and stronger.",
            "vintage": "2014",
            "setting": "With a light, healthy meal",
            "scent": "White grape juice, pear, kiwi, roses, coriander, honeysuckle",
            "sparkling": "",
            "rose": "",
            "wineType": "white",
            "wineBrand": "Rambutan",
            "varietal": "Muscat",
            "originState": "California",
            "originRegion": "Paso Robles",
            "originCountry": "United States",
            "price": "13.00",
            "pairings": [
                "Fish",
                "Shellfish",
                "Sushi",
                "Veggies"
            ],
            "body": [
                "medium"
            ],
            "cider": "",
            "closure": [
                "cork"
            ],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[\"chilled; then let it warm up in the glass\"]",
            "sweetness": [
                "slightly sweet"
            ],
            "tasting_note": [],
            "winemaking": []
        },
        {
            "@search.score": 1,
            "wine_Id": "520",
            "product_Id": "10881",
            "isAvailable": 0,
            "name": "2013 La Muleta Garnacha",
            "shortDescription": "",
            "longDescription": "In France and the U.S. it goes by Grenache, in Sardinia it’s Cannonau, but in Spain you’ll find <a target='_blank' href='http://juice.clubw.com/story/many-different-wine-names'>Garnacha</a>. And there, Jumilla’s location on the Mediterranean coast creates the perfect, warm growing region that Garnacha thrives in. With a little heat the grapes ripen slowly, creating higher sugar levels which lead to higher alcohol levels, adding both <a target='_blank' href='http://juice.clubw.com/jargon/body'>body</a> and spice to the wine (a signature Spanish characteristic). \n\nUsing a combination of both modern technology and traditional methods from the historical winemaking region of Jumilla, La Muleta’s flavors portray an authentic Spanish style with the perfect balance of fresh fruit and a little funkiness. It draws you in with dark berry aromas, but on the palate surprises with <a target='_blank' href='http://juice.clubw.com/jargon/spicy'>spicy</a> flavor, rich <a target='_blank' href='http://juice.clubw.com/jargon/earthy'>earthy</a> notes, mouth-puckering acidity, and subtle <a target='_blank' href='http://juice.clubw.com/jargon/tannins'>tannins</a> that get you on the end just where it counts for a long, dry <a target='_blank' href='http://juice.clubw.com/jargon/finish'>finish</a>.",
            "vintage": "2013",
            "setting": "Date night",
            "scent": "Mixed berries, perfume, moss, poblano pepper, white pepper spice",
            "sparkling": "",
            "rose": "",
            "wineType": "red",
            "wineBrand": "La Muleta",
            "varietal": "Grenache",
            "originState": "",
            "originRegion": "Jumilla",
            "originCountry": "Spain",
            "price": "13.00",
            "pairings": [
                "Beef",
                "Mexican",
                "Cured Meats"
            ],
            "body": [
                "full"
            ],
            "cider": "",
            "closure": [
                "cork"
            ],
            "descriptorFlavor": [],
            "descriptorUnique": [],
            "descriptorStructure": [],
            "descriptor_structure": "[]",
            "how_to_serve": "[\"room temperature\"]",
            "sweetness": [
                "dry"
            ],
            "tasting_note": [],
            "winemaking": []
        }
    ];

var testData = alcohol.map(item => {
    delete item["@search.score"];
    return item;
})

module.exports = {
seedData: function () {
    db.Wines
      .remove({})
      .then(() => db.Wines.collection.insertMany(testData))
      .then(data => {
        console.log(data.insertedIds.length + " records inserted!");
        process.exit(0);
      })
      .catch(err => {
        console.error(err);
        process.exit(1);
      });
    }
}
